// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function read_t(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.string, json),
          /* title */Json_decode.field("item", Json_decode.string, json),
          /* checked */Json_decode.field("checked", Json_decode.bool, json)
        ];
}

function read_response(param) {
  return Json_decode.list(read_t, param);
}

exports.read_t = read_t;
exports.read_response = read_response;
/* No side effect */
